config/routes.rb
Rails.application.routes.draw do
  resources :widget_forms

  root 'welcome#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get  '/logout' => 'sessions#destroy'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :payments
  has_many :widget_forms
end

app/models/widget_form.rb
class WidgetForm < ActiveRecord::Base
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
 helper_method :current_user

 def authorize
   redirect_to '/login' unless current_user
 end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
   user = User.new(user_params)
   if user.save
     session[:user_id] = user.id
     redirect_to '/'
   else
     redirect_to '/signup'
   end
 end

 private
 def user_params
   params.
     require(:user).
     permit(:name,
            :email,
            :password,
            :password_confirmation)
 end

end

app/controllers/widget_forms_controller.rb
class WidgetFormsController < ApplicationController
  before_action :set_widget_form, only: [:show, :edit, :update, :destroy]

  # GET /widget_forms
  # GET /widget_forms.json
  def index
    @widget_forms = WidgetForm.where(user_id: current_user.id)
  end

  # GET /widget_forms/1
  # GET /widget_forms/1.json
  def show
  end

  # GET /widget_forms/new
  def new
    @widget_form = WidgetForm.new
  end

  # GET /widget_forms/1/edit
  def edit
    @widget_form = WidgetForm.find(params[:id])
    if @widget_form.user != current_user
      redirect_to login_path
    end
  end

  # POST /widget_forms
  # POST /widget_forms.json
  def create
    @widget_form = WidgetForm.new(widget_form_params)
    @widget_form.user = current_user

    respond_to do |format|
      if @widget_form.save
        format.html { redirect_to @widget_form, notice: 'Widget form was successfully created.' }
        format.json { render :show, status: :created, location: @widget_form }
      else
        format.html { render :new }
        format.json { render json: @widget_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widget_forms/1
  # PATCH/PUT /widget_forms/1.json
  def update
    respond_to do |format|
      if @widget_form.update(widget_form_params)
        format.html { redirect_to @widget_form, notice: 'Widget form was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget_form }
      else
        format.html { render :edit }
        format.json { render json: @widget_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widget_forms/1
  # DELETE /widget_forms/1.json
  def destroy
    @widget_form.destroy
    respond_to do |format|
      format.html { redirect_to widget_forms_url, notice: 'Widget form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget_form
      @widget_form = WidgetForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_form_params
      params.require(:widget_form).permit(:title_text, :background_color, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widget_forms_helper.rb
module WidgetFormsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WidgetApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/widget_forms/_form.html.erb
<%= form_for(@widget_form) do |f| %>
  <% if @widget_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget_form.errors.count, "error") %> prohibited this widget_form from being saved:</h2>

      <ul>
      <% @widget_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_text %><br>
    <%= f.text_field :title_text %>
  </div>
  <div class="field">
    <%= f.label :background_color %><br>
    <%= f.text_field :background_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widget_forms/edit.html.erb
<h1>Editing Widget Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget_form %> |
<%= link_to 'Back', widget_forms_path %>

app/views/widget_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Widget Forms</h1>

<table>
  <thead>
    <tr>
      <th>Title text</th>
      <th>Background color</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widget_forms.each do |widget_form| %>
      <tr>
        <td><%= widget_form.title_text %></td>
        <td><%= widget_form.background_color %></td>
        <td><%= widget_form.user %></td>
        <td><%= link_to 'Show', widget_form %></td>
        <td><%= link_to 'Edit', edit_widget_form_path(widget_form) %></td>
        <td><%= link_to 'Destroy', widget_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget form', new_widget_form_path %>

app/views/widget_forms/new.html.erb
<h1>New Widget Form</h1>

<%= render 'form' %>

<%= link_to 'Back', widget_forms_path %>

app/views/widget_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title text:</strong>
  <%= @widget_form.title_text %>
</p>

<p>
  <strong>Background color:</strong>
  <%= @widget_form.background_color %>
</p>

<p>
  <strong>User:</strong>
  <%= @widget_form.user %>
</p>

<%= link_to 'Edit', edit_widget_form_path(@widget_form) %> |
<%= link_to 'Back', widget_forms_path %>